// <auto-generated />
using System;
using FinanceTracker.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceTracker.DataAccess.Migrations
{
    [DbContext(typeof(FinanceTrackerDbContext))]
    [Migration("20260519150524_AdminContent")]
    partial class AdminContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Budget.BudgetData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Limit")
                        .HasColumnType("numeric");

                    b.Property<string>("Month")
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .HasColumnType("text");

                    b.Property<decimal>("Spent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Content.CurrencyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f980db-7a51-4029-9f7d-0ecfd28c36d9"),
                            Code = "USD",
                            Name = "US Dollar",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("0d6b12da-4f7f-4dc2-8408-1b8b3a2f1b62"),
                            Code = "EUR",
                            Name = "Euro",
                            Symbol = "EUR"
                        },
                        new
                        {
                            Id = new Guid("93e0f605-7a4a-46c7-8c24-0b029add2f2d"),
                            Code = "GBP",
                            Name = "British Pound",
                            Symbol = "GBP"
                        },
                        new
                        {
                            Id = new Guid("b71ab74a-2dc3-4f91-9d61-dbc9a9f0f1f5"),
                            Code = "MDL",
                            Name = "Moldovan Leu",
                            Symbol = "lei"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Content.ExpenseCategoryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ExpenseCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b93ed8a-5025-4f4e-8a26-5d69f9fae3a6"),
                            Key = "food",
                            Label = "Food & Groceries"
                        },
                        new
                        {
                            Id = new Guid("4765462e-b2e0-4031-8b32-4e44edfa9b65"),
                            Key = "transport",
                            Label = "Transport"
                        },
                        new
                        {
                            Id = new Guid("8f4c9b10-44f5-4f9e-8eaa-3d19a5b241d6"),
                            Key = "entertainment",
                            Label = "Entertainment"
                        },
                        new
                        {
                            Id = new Guid("5bd9f47d-85c7-4c81-88e1-7031c48a8de0"),
                            Key = "shopping",
                            Label = "Shopping"
                        },
                        new
                        {
                            Id = new Guid("c19b9f8a-dc5c-4a78-9a8a-60d7b5e0f2f4"),
                            Key = "bills",
                            Label = "Bills & Utilities"
                        },
                        new
                        {
                            Id = new Guid("7d4097d0-28f3-4bdb-a889-2a9d6b93659c"),
                            Key = "health",
                            Label = "Health"
                        },
                        new
                        {
                            Id = new Guid("e0a6e7ad-7c47-42e3-8e3b-2b3d93fdd59f"),
                            Key = "education",
                            Label = "Education"
                        },
                        new
                        {
                            Id = new Guid("5466d601-e99f-4d04-bebc-3d6a1f75e3db"),
                            Key = "travel",
                            Label = "Travel"
                        },
                        new
                        {
                            Id = new Guid("ed1e9a1b-4d55-4e9d-b682-86c75d3b5ad1"),
                            Key = "other",
                            Label = "Other"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Content.IncomeCategoryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("IncomeCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1ab1f76-00ea-48a9-9e78-1ac9a8182fbd"),
                            Key = "salary",
                            Label = "Salary"
                        },
                        new
                        {
                            Id = new Guid("3bcb7c1b-4ab7-4c8c-9b2e-1a2dc7135e17"),
                            Key = "freelance",
                            Label = "Freelance"
                        },
                        new
                        {
                            Id = new Guid("c61c4b6b-9782-4c4a-b734-4f6f2945f0c2"),
                            Key = "investment",
                            Label = "Investment"
                        },
                        new
                        {
                            Id = new Guid("f0c2ff2f-113a-43fb-9874-4b7b8b60c2c9"),
                            Key = "bonus",
                            Label = "Bonus"
                        },
                        new
                        {
                            Id = new Guid("c5f1b61a-2a52-4d4f-87b3-3f3e2d9f7568"),
                            Key = "gift",
                            Label = "Gift"
                        },
                        new
                        {
                            Id = new Guid("d8a1ff0b-22bb-4d0b-9b03-2c80bf1d5a6e"),
                            Key = "other_income",
                            Label = "Other Income"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Content.TransactionStatusData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("TransactionStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6d8d6a6-7378-4c0d-9a16-63d7f91cd1f1"),
                            Color = "#10b981",
                            Label = "Completed",
                            Value = "completed"
                        },
                        new
                        {
                            Id = new Guid("2b64c0a2-60b4-4a3b-9f56-9f581b5b5b43"),
                            Color = "#f59e0b",
                            Label = "Pending",
                            Value = "pending"
                        },
                        new
                        {
                            Id = new Guid("0b9b3aa5-8aa6-4a4b-8c5a-2d91c46d59b5"),
                            Color = "#ef4444",
                            Label = "Cancelled",
                            Value = "cancelled"
                        });
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Expense.ExpenseData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.Income.IncomeData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FinanceTracker.Domain.Entities.User.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
